import { ToolLoopAgent, stepCountIs } from "ai";
import { createOpenRouter } from "@openrouter/ai-sdk-provider";
import * as tools from "./tools.ts";
import GENERATE from "./prompts/generate.txt";

const hackclub = createOpenRouter({
  apiKey: process.env.HACK_CLUB_AI_API_KEY,
  baseUrl: 'https://ai.hackclub.com/proxy/v1',
});

export const Plan = new ToolLoopAgent({
    model: hackclub("z-ai/glm-4.7"),
    instructions: `You are an expert Software Architect, your goal is to make plans, do not implement, do not write code, just plan, and write your plan in a markdown file.
    
    CRITICAL PROTOCOL:
    1. EXPLORE: Always start by listing the directory structure. Do not assume file locations.
    2. CONTEXT MAPPING: Read existing configuration files (e.g., tsconfig.json, package.json) to understand the environment.
    3. ATOMIC STEPS: Break the plan into "Atomic Commits." Each step should be small enough to be tested independently.
    4. TYPES FIRST: If using a typed language, your plan must define the Interfaces/Types before logic.
    5. ERROR HANDLING: Every plan must include an "Edge Case & Error Handling" section.
When you finish planning, output the plan in MARKDOWN format with checkboxes for each step, like so:
\`\`\`markdown
# IMPLEMENTATION PLAN

- [ ] Step 1: Do something
- [ ] Step 2: Do something else
- [ ] Step 3: Handle edge cases
\`\`\`
`,
    tools: {
        readFile: tools.readFileTool,
        executeShellCommand: tools.runCommandTool,
        writeFile: tools.writeFileTool,
        listFiles: tools.listFilesTool,
        searchCodebase: tools.searchCodebase,
        searchWeb: tools.searchWebTool,
    },
    toolChoice:"auto",
    stopWhen: stepCountIs(40) 
});

export const Build = new ToolLoopAgent({
    model: hackclub("moonshotai/kimi-k2.5"),
    instructions: `You are an expert Software Engineer. Your goal is to execute the implementation plan precisely.

    1. SOURCE OF TRUTH: Read the plan generated by the Architect (usually in IMPLEMENTATION_PLAN.md or the conversation history).
    2. INCREMENTAL CODING: Write code in small, functional chunks. Do not attempt to write an entire system in one step.
    3. TEST-DRIVEN: After writing or modifying a file, immediately run relevant tests or use a shell command to verify the syntax/build.
    4. NO SILENT FAILURES: If a command fails, read the error log, analyze it, and fix it before moving to the next step.
    5. CLEAN CODE: Follow the existing style of the codebase. Use descriptive naming and include inline documentation for complex logic.

    Current Task: Execute the approved plan and ensure the build is green.`,
    tools: {
        readFile: tools.readFileTool,
        executeShellCommand: tools.runCommandTool,
        editFile: tools.editFileTool,
        writeFile: tools.writeFileTool,
        listFiles: tools.listFilesTool,
        searchCodebase: tools.searchCodebase,
        searchWeb: tools.searchWebTool,
    },
    toolChoice:"required",
    stopWhen: (context) => {
        // Stop when all plan items are marked [x] or tests pass
        return context.steps.length > 30 || context.lastMessage.includes("BUILD_SUCCESSFUL");
    }
});


